### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by nailyk-fr** [drk1wi/portspoof#22]
Portspoof (builded after this [commit](6ba137854564df50baef6e7481e7e2171a55b9bd)) randomly crash very often. I start it with this command line from non root user: 
`./root/bin/portspoof -c ./root/etc/portspoof.conf -s ./root/etc/portspoof_signatures`

I know an issue without log is a pain but it crashing two or tree times a day with no output :s  
Is it possible to enable some debug to provide logs? Where can I enable them? 

My old version (1.3 - 26/06/2014) had less crash (one or two times a week) and sometimes output with 'Send to socket failed: Connection reset by peer' Don't know if it help. 
```
gcc (Debian 4.9.2-10) 4.9.2
debian 8.6
iptables -A PREROUTING -i eth0 -p tcp -m tcp --dport 123456 -j RETURN
iptables -A PREROUTING -i eth0 -p tcp -m tcp --dport 1:65535 -j REDIRECT --to-ports 4444

```
Not related to the issue: Thanks for provide this awesome tool! Great work! I hope support will be back :)

**Comment by drk1wi** [comment]
Hey nailyk,

Could you configure the app using the latest source code with the following command:
./configure CFLAGS="-ggdb3 -O0" CXXFLAGS="-ggdb3 -O0" LDFLAGS="-ggdb3"
then make and before running portspoof enable dumps with this command ulimit -c unlimited.

It should then generate coredumps. Please send me all of them and I will try to fix this issue :)

**Comment by nailyk-fr** [comment]
Thanks for your quick answer. 
Sorry, I probably did something wrong: 

```
portspoof@hostname :) % ulimit -c unlimited 
portspoof@hostname :) % ./root/bin/portspoof -c ./root/etc/portspoof.conf -s ./root/etc/portspoof_signatures && ./mail || ./mail
-> Using user defined configuration file ./root/etc/portspoof.conf
-> Using user defined signature file ./root/etc/portspoof_signatures
zsh: segmentation fault (core dumped)  ./root/bin/portspoof -c ./root/etc/portspoof.conf -s
portspoof@hostname :) % 
```
Running from bash provide the same result. 

Sounds like dmesg provide this at crash time: 
```
11930601.318288] traps: portspoof[2487] general protection ip:40c2d3 sp:7ffed24ecd70 error:0 in portspoof[400000+17000]
```
and dmesg when run from bash: 
`11932167.203194] portspoof[4397]: segfault at 7f01d6aabd68 ip 000000000040aebe sp 00007ffed6aab8e0 error 4 in portspoof[400000+17000]`

How I rebuild: 
```
make clean
./configure --prefix=/home/portspoof/root CFLAGS="-ggdb3 -O0" CXXFLAGS="-ggdb3 -O0" LDFLAGS="-ggdb3"
make
sudo make install
```

(I bet on specific ip packets for those crash. While writing this answer portspoof keep crashing (see [screenshot](https://cloud.githubusercontent.com/assets/16372405/19988066/8f67d33c-a21e-11e6-8909-6de5932a9029.png)) so I should be under a specific scan/attack. I tried to tcpdump. Will edit my comment as soon as I have inspected the tcpdump sniff. )

**Comment by drk1wi** [comment]
Thanks nailyk, I am working on this.

**Comment by nailyk-fr** [comment]
Hi, 
Any news? 
Do you need more core dumps? What could I try to help you? 
If you can give me an entry point into the code I should be able to add some printf to identify the problem. 
Thanks in advance.

**Comment by drk1wi** [comment]
Hey,

I have fixed the issue. Tomorrow I will upload the new version. 
Thanks for your help.

Piotr

**Comment by nailyk-fr** [comment]
Just rebuilt. 
Thanks for the fix.

**Comment by nailyk-fr** [comment]
I still have a lot of 
> Send to socket failed: Connection reset by peer

but this make it rock-solid: 
> portspo+ 18682  0.4  1.2 768520 19300 pts/3    Sl+  **mars10** 208:20 ./root/bin/portspoof -c ./root/etc/portspoof.conf -s ./root/etc/portspoof_signatures

Thanks for the fix :)
